name: Scrape latest wikidata

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Prepare
      run: pip install -r requirements.txt
    - name: Fetch latest data and create csv
      run: |-
        make
    
