name: Scrape latest wikidata

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      DW_TOKEN: "${{secrets.DW_TOKEN}}"
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Prepare
      run: pip install -r requirements.txt
    - name: Fetch latest data and create csv
      run: |-
        make
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add nuts-merged-count.csv zeitungen-mit-nuts.csv changelog.md
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Upload changed data
      run: |-
        python upload-datawrapper.py

    
